apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-furizugl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-api
        image: fakhririzkianag/furizu_game_list-backend:latest
        imagePullPolicy: Always
        env:
        - name: NAMA_PRAKTIKAN
          value: "Fakhri Rizkiana"
        - name: NIM_PRAKTIKAN
          value: "2405534"
        # --- TAMBAHAN MODUL 2 ---
        livenessProbe:      # Mengecek apakah aplikasi hang
          httpGet:
            path: /api/info
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 15
        readinessProbe:     # Mengecek apakah aplikasi siap terima traffic
          httpGet:
            path: /api/info
            port: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-furizugl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-ui
        image: fakhririzkianag/furizu_game_list-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
